### ISSUE TITLE
[BUG] Multiple precompiled assemblies with the same name

### ISSUE THREAD

**Issue by iamabigartist** [kumaS-nu/NuGet-importer-for-Unity#13]
2020.3.25f1:
I try to install Microsoft.CSharp.Scripting 3.11.0, and the compile error below.
![image](https://user-images.githubusercontent.com/53459343/147413781-1b4425b4-cc88-4dfe-bfe1-a0292b055670.png)

It seems a problem only for Microsoft's packages.

**Comment by kumaS-nu** [comment]
Umm... I think this is caused by package localization (multi-language support). I need to check the configuration of .nupkg, so it may take some time. （I hope to finish it by the end of this year.)

**Comment by iamabigartist** [comment]
yeah yeah, it's not the problem from this plugin, using other NuGet package managers to install this will cause this as well. Maybe you can work it out with other authors.
[Creating localized NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages)

**Comment by kumaS-nu** [comment]
I've fixed it to avoid errors. Analyzers are now saved in `(your project)/NuGet`, so you can add them manually.
