### ISSUE TITLE
[BUG] Unity 2021.2 に導入不可

### ISSUE THREAD

**Issue by hideki-fujiwara** [kumaS-nu/NuGet-importer-for-Unity#15]
Git URL を指定する方法で導入しています。コンパイルエラーが表示され、期待している動作がしません。

下記のエラーが表示されます。
[Error] 'ApiCompatibilityLevel' does not contain a definition for 'NET_4_8'
[Error] The switch statement contains multiple cases with the label value '6'

環境 :
 - OS: Windows 10 Pro 21H1
 - Unity Version 2021.2.11f1
 - Package Version 2.1.0

FrameworkName.cs
辺りを弄るも解決に至らず・・・すみませんが解決策を教えてください。

※Unity Version 2020.3.27f1では利用できています。

**Comment by kumaS-nu** [comment]
報告ありがとうございます．
新しいバージョンの検証不足で名前が間違ってました......
すぐ修正します．
