### ISSUE TITLE
[BUG] Thumbnails fail to render on Unity OpenGL back end

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#18]
**Describe the bug**
If Unity is set to use the OpenGL back end, as is the default on Linux, thumbnails for packages don't show up.

**To Reproduce**
1. Go to 'NuGet Importer'
2. Click on 'Manage Packages'
3. See error in Unity console.

**Expected behavior**
The thumbnails display properly.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/73220431/156781835-ffb9c294-1424-402f-bab7-e37b2a12b5df.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86-64
 - Unity Version: 2020.3.26f1
 - Package Version: 2.3.1

**Additional context**
The logs of the error in the console, which are repeated many times (probably once per thumbnail):

```
OPENGL: Graphics.CopyTexture called on textures with different mip count (8 vs 7)?
UnityEngine.Graphics:ConvertTexture (UnityEngine.Texture,UnityEngine.Texture)
kumaS.NuGetImporter.Editor.PackageDataExtentionToGUI/<GetIcon>d__12:MoveNext () (at Library/PackageCache/org.kumas.nuget-importer@2.1.1/Editor/PackageDataExtentionToGUI.cs:592)
System.Reflection.MethodBase:Invoke (object,object[])
Microsoft.MixedReality.Toolkit.Utilities.SyncContextUtility:ExecuteContinuations () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.7.3/Core/Utilities/Async/Internal/SyncContextUtility.cs:53)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

OPENGL: Graphics.CopyTexture called on textures of different sizes?
UnityEngine.Graphics:ConvertTexture (UnityEngine.Texture,UnityEngine.Texture)
kumaS.NuGetImporter.Editor.PackageDataExtentionToGUI/<GetIcon>d__12:MoveNext () (at Library/PackageCache/org.kumas.nuget-importer@2.1.1/Editor/PackageDataExtentionToGUI.cs:592)
System.Reflection.MethodBase:Invoke (object,object[])
Microsoft.MixedReality.Toolkit.Utilities.SyncContextUtility:ExecuteContinuations () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.7.3/Core/Utilities/Async/Internal/SyncContextUtility.cs:53)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

**Comment by kumaS-nu** [comment]
Thank you your report.
It seems that the thumbnail resizing is failing.
I'll fix it in a week.

**Comment by kumaS-nu** [comment]
@NoTuxNoBux 
The mipmap that is causing the error is not needed in this package, so I changed to not create it.
I don't have the environment where that error occurs right now, so if you don't mind, would you try the fixed version in the develop branch?

**Changed point**
[NuGetImporterForUnity/Packages/NuGet Importer/Editor/PackageDataExtentionToGUI.cs l.587-593](https://github.com/kumaS-nu/NuGet-importer-for-Unity/commit/566a2557614eab102d002aa82e228d7fb6f9bace)
```    diff 
private static async Task GetIcon(string url)
        {
-           var source = new Texture2D(0, 0);
+           var source = new Texture2D(0, 0, TextureFormat.RGBA32, false);
            source.LoadImage(await client.GetByteArrayAsync(url));
-           var texture = new Texture2D(128, 128);
+           var texture = new Texture2D(128, 128, TextureFormat.RGBA32, false);
            Graphics.ConvertTexture(source, texture);
            MonoBehaviour.DestroyImmediate(source);
```

**Comment by NoTuxNoBux** [comment]
Hi @kumaS-nu 

I can confirm latest `develop` with this commit seems to fix it:

![afbeelding](https://user-images.githubusercontent.com/73220431/157198886-ecd93d1b-390b-4d47-92e5-0e5be65a6df0.png)

Thanks!
