### ISSUE TITLE
[BUG] NuGet dependencies are not installed along with package

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#21]
**Describe the bug**
Installing a package does not automatically (always?) install its dependencies.

**To Reproduce**
1. Go to the NuGet Importer package gallery.
2. Install `Microsoft.MixedReality.QR` version `0.5.3013`.
3. Click "Yes" when the package warns that the project is set to .NET Standard 2.0, but the package requires .NET Framework.
4. The package is installed, but `Microsoft.VCRTForwarders.140` isn't, which is [listed as depedency](https://www.nuget.org/Packages/Microsoft.MixedReality.QR).

**Expected behavior**
Package dependencies are installed along with packages, and their dependencies as well, all the way down the tree.

**Desktop (please complete the following information):**
 - OS: Linux x86-64
 - Unity Version: 2020.3.26f1
 - Package Version: 2.1.2

**Additional context**
I'm trying to migrate an existing code base using [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) to this project, and it does (did) correctly install the dependencies.

I can still install the dependencies manually, but I need to assess manually what dependencies are necessary, which is cumbersome, and error-prone - if I forget, I may have runtime errors or compile-time errors (the former are worse since they might only show up in a corner case).

I'm not sure if this is already supposed to be working or not, or if it's not implemented yet. If it is supposed to be working, perhaps it's related to my project being set to use .NET Standard 2.0 and the package requiring .NET Framework? Although the package itself lists .NET Standard 2.0 as being supported, so I'm not sure why I got the warning (that may be another bug).

**Comment by NoTuxNoBux** [comment]
I may have been too fast.

Trying to install [Microsoft.VCRTForwarders.140](https://www.nuget.org/packages/Microsoft.VCRTForwarders.140/) warns that I'm about to uninstall the package, but I never installed it, and the UI doesn't mention it is installed. Perhaps the dependencies _are_ installed, but it's not reflected in the UI?

Installing FakeItEasy 7.3.1 also correctly installs its dependency Castle.Core.

**Comment by kumaS-nu** [comment]
This is caused by a bug in the way dependencies resolve. The resolution of dependency packages for "all" framework is undefined. In addition, since the estimation of the framework used in the package is based on its dependencies, if an error occurred, the estimation would fail.

I'll fix it within a week.
