### ISSUE TITLE
[BUG] Warning shown about compatible packages

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#22]
**Describe the bug**
When the project is set to .NET Standard 2.0, and the package is compatible with .NET Standard 2.0, [a warning is still shown](https://github.com/kumaS-nu/NuGet-importer-for-Unity/blob/9c60c68bf4a2c68e5cb0b1c82e5ef799e6317613/NuGetImporterForUnity/Packages/NuGet%20Importer/Editor/PackageManager.cs#L1098).

**To Reproduce**
1. Set the project to use API level .NET Standard 2.0.
2. Try to install `Microsoft.MixedReality.QR` version `0.5.3013`.
3. See warning.

**Expected behavior**
No warning is printed, as [the package is compatible with .NET Standard 2.0](https://www.nuget.org/Packages/Microsoft.MixedReality.QR) as well.

**Desktop (please complete the following information):**
 - OS: Linux x86-64
 - Unity Version: 2020.3.26f1
 - Package Version 2.1.2

**Additional context**
Not a major problem, just a minor paper cut :slightly_smiling_face: .

**Comment by kumaS-nu** [comment]
As with #21, this is caused by a failure to estimate the framework used by the package.
