### ISSUE TITLE
[BUG] Unity still recompiles scripts when cancelling various actions 

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#23]
**Describe the bug**
When cancelling actions by closing dialog boxes such as "There is no available version", Unity still recompiles scripts unnecessarily (as nothing happened).

**To Reproduce**
1. Make sure "Include development versions" is **not** enabled (the default).
2. Try to install FakeItEasy 7.3.1.
3. See message "There is no available version."
4. Click OK.
5. Unity starts recompiling scripts.

**Expected behavior**
Unity does not recompile scripts.

**Desktop (please complete the following information):**
 - OS: Linux x86-64
 - Unity Version: 2020.3.26f1
 - Package Version 2.1.2

**Additional context**
Not a major problem, just a minor paper cut :slightly_smiling_face: .

**Comment by kumaS-nu** [comment]
There was no need to add a process for canceling, so it was left the same as other operations. While fixing the bug, I will change it so that it does the proper processing when canceling.
