### ISSUE TITLE
[BUG] Central Directory Corrupt

### ISSUE THREAD

**Issue by iamabigartist** [kumaS-nu/NuGet-importer-for-Unity#29]
**Describe the bug**
Try to install **Microsoft.CodeAnalysis.Common** package, and after downloading, get this:

**Screenshots**
![image](https://user-images.githubusercontent.com/53459343/167882428-8e749ecc-4425-44e2-ad09-9dd4f0106e8f.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Unity Version 2021.2.16f1
 - Package Version 2.2.0

**Comment by kumaS-nu** [comment]
Thank you for the report.
The bug was caused by a change in HttpClient streaming download specification from Unity2021.
I fixed the bug and would be glad if you could let me know whether this package worked without any problems.
