### ISSUE TITLE
Automatically activate Roslyn analyzers in NuGet packages in Unity

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#31]
**Is your feature request related to a problem? Please describe.**
Unity [supports running Roslyn analyzers which can be installed through NuGet](https://docs.unity3d.com/2020.2/Documentation/Manual/roslyn-analyzers.html). The main downside in Unity is that they recommend grabbing the DLL from the NuGet package and dropping it in your project, which is unfortunate since it doesn't allow automatic updating of the package, and forces you to include packages in version control.

**Describe the solution you'd like**
When a package containing Roslyn analyzers is installed, they are automatically registered with Unity as roslyn analyzers.

**Describe alternatives you've considered**
Installing them manually the Unity way or making a script to install them (which is what I'm doing for the moment).

**Additional context**
Examples of such packages include [Roslynator](https://github.com/JosefPihrt/Roslynator), [ErrorProne](https://github.com/SergeyTeplyakov/ErrorProne.NET/), and [Microsoft Unity Analyzers](https://github.com/microsoft/Microsoft.Unity.Analyzers).

Automating this comes down to the following:

1. Download and extract the NuGet package (already happens).
2. Search for analyzer DLLs in the package, copy them to the `Assets/Scripts/Foo` folder (or another folder that is picked up by Unity).
3. Either generate or update a matching meta file for each DLL that has the `RoslynAnalyzer` label set (or Unity will not recognize the DLL as an analyzer).

I'm not sure how to recognize DLLs that are analyzers as opposed to regular assemblies for step 2, but looking at the above examples, they all use subfolders `analyzers/dotnet/cs` to store these DLLs in.

If users do not want to run these analyzers automatically (as their errors block play mode), they can simply disable Roslyn analyzer support in the Unity project settings, so it should be safe to always do this.

Finally, an added bonus to this is that Unity (2020 and up) will also put these analyzers in C# project files generated for e.g. VSCode, so OmniSharp will also be able to use them.

**Comment by kumaS-nu** [comment]
Good feature request.
It is difficult to recognize exactly the analyzer since the official NuGet package structure did not include it. As you say, we may assume that the analyzer is the one in a folder such as `analyzers/dotnet/cs`.
I can implement the automatic addition of the analyzer by doing something like [CsprojModifier](https://github.com/Cysharp/CsprojModifier), but it's not very pretty, so I'll think about it some more.

**Comment by kumaS-nu** [comment]
Sorry for the very late reply...
I implemented the installation of Roslyn Analyzer.
`.dlls` under `analyzers/dotnet/cs` are installed as Roslyn Analyzer.
I have not tested Rider, so I don't know, but it worked fine in VS and VSCode.
