### ISSUE TITLE
[BUG] Error at Installing Microsoft.Win32.Registry package

### ISSUE THREAD

**Issue by IvanMurzak** [kumaS-nu/NuGet-importer-for-Unity#33]
# Can't install `Microsoft.Win32.Registry` package version 5.0.0

**To Reproduce**
1. Go to 'NuGet importer'
2. Type `Microsoft.Win32.Registry`
3. Choose version 5.0.0
4. Press `Install`

**Expected behavior**
Success installation

**Screenshots**
![image](https://user-images.githubusercontent.com/9135028/171218141-f17957e9-a8d5-43d5-89e0-20e0d001c615.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - Unity Version [e.g. 2020.3.25f1]
 - Package Version [e.g. 2.2.1]

**Comment by kumaS-nu** [comment]
Sorry for the very late reply...
This error message is a failure to connect to the network.
The error message displayed in the dialog is unclear, so I will change that the exception details are also output to the Unity console.
