### ISSUE TITLE
Support SDK-style projects

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#38]
**Is your feature request related to a problem? Please describe.**
Unity has decided [to drop support for the VSCode package](https://forum.unity.com/threads/update-on-the-visual-studio-code-package.1302621/). A community alternative has [already surfaced](https://github.com/Unity-Technologies/com.unity.ide.vscode/issues/19#issuecomment-1186849147), and supports modern SDK-style C# projects. When using SDK-style projects, however, this package breaks immediately on start-up because `OnGeneratedCSProject.OnGeneratedCSProject` tries to parse the project.

**Describe the solution you'd like**
Support for newer SDK-style projects.

**Describe alternatives you've considered**
Stick to the old Unity package.

**Additional context**
Since support has been dropped, it's only a matter of time before the community fork becomes the de facto standard. SDK-style projects have been the default for .NET projects for years now, but Unity was lagging behind in supporting only legacy-style projects.

Also, use of SDK-style projects allows gaining substantially improved performance in tools such as OmniSharp by using modern .NET 6 builds.

Error thrown by the package when using a modern SDK-style project:

```
NullReferenceException: Object reference not set to an instance of an object
kumaS.NuGetImporter.Editor.NuGetAnalyzerImportSetting.OnGeneratedCSProject (System.String path, System.String content) (at Library/PackageCache/org.kumas.nuget-importer@2.3.1/Editor/NuGetAnalyzerImportSetting.cs:118)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <8516445456524a6cb20c4b3b7de67982>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <8516445456524a6cb20c4b3b7de67982>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <8516445456524a6cb20c4b3b7de67982>:0)
VSCodeEditor.ProjectGeneration.InvokeAssetPostProcessorGenerationCallbacks (System.String name, System.String path, System.String content) (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:237)
VSCodeEditor.ProjectGeneration.OnGeneratedCSProject (System.String path, System.String content) (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:250)
VSCodeEditor.ProjectGeneration.SyncProjectFileIfNotChanged (System.String path, System.String newContents) (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:435)
VSCodeEditor.ProjectGeneration.SyncProject (UnityEditor.Compilation.Assembly assembly, System.Collections.Generic.Dictionary`2[TKey,TValue] allAssetsProjectParts, System.Collections.Generic.List`1[T] responseFilesData) (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:428)
VSCodeEditor.ProjectGeneration.GenerateAndWriteSolutionAndProjects () (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:348)
VSCodeEditor.ProjectGeneration.Sync () (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/ProjectGeneration/ProjectGeneration.cs:261)
VSCodeEditor.VSCodeScriptEditor.SyncAll () (at Library/PackageCache/com.unity.ide.vscode@67c02d0abf/Editor/VSCodeScriptEditor.cs:170)
UnityEditor.CodeEditorProjectSync.SyncEditorProject () (at /home/bokken/buildslave/unity/build/Editor/Mono/CodeEditor/CodeEditorProjectSync.cs:21)
```

**Comment by kumaS-nu** [comment]
Thank you for the great suggestion. I'll support it in the next feature update.

**Comment by NoTuxNoBux** [comment]
Looking at this error again, I'm wondering: if I understand correctly, the code will add analyzers that don't exist yet in the C# project to the list, but... why is this necessary exactly?

I understand the analyzers have to be included in the `.csproj` in order for them to be used, but doesn't Unity do this automatically? If this package creates a meta file for the DLLs it installs through NuGet with the appropriate tag:

```
fileFormatVersion: 2
guid: SOME_META_ASSET_GUID
labels:
- RoslynAnalyzer
PluginImporter:
   ....
```

... then Unity will/should automatically pick them up, and the VSCode package will automatically append them to the `csproj` by itself. This should work for both the legacy/deprecated VSCode package as well as the new one, but I don't know about the Rider and Visual Studio packages, though.

**Comment by kumaS-nu** [comment]
As you wrote, VSCode automatically adds the Analyzer, but at least Visual Studio does not, so it is necessary to add the Analyzer to the project file. (Not sure about Rider).
I've already written the SDK-style project file support, so I'll add that change.
