### ISSUE TITLE
Unity 2020.3.0f1 (LTS) で動作しない

### ISSUE THREAD

**Issue by TytoMan** [kumaS-nu/NuGet-importer-for-Unity#4]
**UPMを使用した場合**
使用法 に記載されている通りUPMでプロジェクトにインストールすると以下のエラーが出て使用できない。

`Library\PackageCache\org.kumas.nuget-importer@3e0d604704\Editor\PackageManager.cs(855,13): error CS0103: The name 'ZipFile' does not exist in the current context`

**.unitypackageを使用した場合**
使用法 に記載されているとおりに.unitypackageをプロジェクトにインストールする。
NuGet Importer > Manage Packages をクリックするとメインウィンドウは開かず以下のエラーが出て使用できない。

`ArgumentException: method return type is incompatible
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.CreateDelegate (System.String methodName) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.HostView.CreateDelegates () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.HostView.SetActualViewInternal (UnityEditor.EditorWindow value, System.Boolean sendEvents) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.DockArea.SetSelectedPrivate (System.Int32 value, System.Boolean sendEvents) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.DockArea.AddTab (System.Int32 idx, UnityEditor.EditorWindow pane, System.Boolean sendPaneEvents) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.DockArea.AddTab (UnityEditor.EditorWindow pane, System.Boolean sendPaneEvents) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.CreateNewWindowForEditorWindow (UnityEditor.EditorWindow window, System.Boolean loadPosition, System.Boolean showImmediately, System.Boolean setFocus) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.Show (System.Boolean immediateDisplay) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.Show () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.GetWindowPrivate (System.Type t, System.Boolean utility, System.String title, System.Boolean focus) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.GetWindow (System.Type t, System.Boolean utility, System.String title, System.Boolean focus) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.GetWindow[T] (System.Boolean utility, System.String title, System.Boolean focus) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.EditorWindow.GetWindow[T] () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
kumaS.NuGetImporter.Editor.NuGetImporterWindow.ShowWindow () (at <0353acf8ba8b4dc8be80bf2737c008d8>:0)`

**環境**
 - OS: Windows 10 Home 2004
 - Unity: Version 2020.3.0f1
 - Package: Version 1.1.0

**その他**
Unity 2019.4.22f1では正常に動作しています。

**Comment by kumaS-nu** [comment]
いろいろ調べてみたところ Unity の内部の挙動が変わって、Unity のメゾッドは指定の返り値（今回は void ）でないとエラーとなるように変わったみたいです。
そこを直してみたのですが、今度はウィンドウが出なくなったので修正には少し時間がかかりそうです。
修正はちゃんとするのでお待ちください。

**Comment by kumaS-nu** [comment]
ウィンドウが出なかったのはウィンドウのサイズが初期設定されてなかったからでした。
v1.1.1として修正を上げます。
