### ISSUE TITLE
[BUG] Some search terms break search

### ISSUE THREAD

**Issue by NoTuxNoBux** [kumaS-nu/NuGet-importer-for-Unity#45]
**Describe the bug**
If I open the package window and enter specific terms to search, errors are posted every second or so and no results appear.

**To Reproduce**
1. Open the search window.
2. Type `Microsoft.MixedReality.QR`.
3. Press enter/return.

**Expected behavior**
The expected results appear.

**Desktop (please complete the following information):**
 - OS: Linux x86-64
 - Unity Version: 2021.3.6f1
 - Package Version 2.3.2

**Additional context**
The error that is posted is the following:

```
You cannot call GetLast immediately after beginning a group.
UnityEngine.GUILayoutUtility:GetLastRect ()
kumaS.NuGetImporter.Editor.NuGetImporterWindow:OnGUI () (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/NuGetImporterWindow.cs:427)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /home/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

**Comment by NoTuxNoBux** [comment]
I don't know if it's a coincidence, but if I search for just `QR`, I do not get these errors, but it gets stuck on "Organizing datas", presumably because there are some packages it can't fetch something for:

```
HttpRequestException: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () (at <a07a075638bc4ba8988cc7cdce08093f>:0)
System.Net.Http.HttpClient.GetByteArrayAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) (at <a07a075638bc4ba8988cc7cdce08093f>:0)
kumaS.NuGetImporter.Editor.PackageDataExtentionToGUI.GetIcon (System.String url) (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/PackageDataExtentionToGUI.cs:650)
kumaS.NuGetImporter.Editor.PackageDataExtentionToGUI.GetIcon (System.String url) (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/PackageDataExtentionToGUI.cs:667)
kumaS.NuGetImporter.Editor.PackageDataExtentionToGUI.GetIcon (kumaS.NuGetImporter.Editor.DataClasses.Datum data) (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/PackageDataExtentionToGUI.cs:236)
kumaS.NuGetImporter.Editor.NuGetImporterWindow.UpdateData () (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/NuGetImporterWindow.cs:332)
UnityEngine.Debug:LogException(Exception)
kumaS.NuGetImporter.Editor.<UpdateData>d__34:MoveNext() (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/NuGetImporterWindow.cs:341)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetException(Exception)
kumaS.NuGetImporter.Editor.<GetIcon>d__10:MoveNext() (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/PackageDataExtentionToGUI.cs:242)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetException(Exception)
kumaS.NuGetImporter.Editor.<GetIcon>d__16:MoveNext() (at Library/PackageCache/org.kumas.nuget-importer@2.3.2/Editor/PackageDataExtentionToGUI.cs:675)
System.Reflection.MethodBase:Invoke(Object, Object[])
Microsoft.MixedReality.Toolkit.Utilities.SyncContextUtility:ExecuteContinuations() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@2.8.0/Core/Utilities/Async/Internal/SyncContextUtility.cs:53)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)
```

**Comment by kumaS-nu** [comment]
This error occurs when the search results show that there are packages in the development version, but none of them are in the stable version. (I'll fix it.)

I thought I fixed the 404 issue with this commit(https://github.com/kumaS-nu/NuGet-importer-for-Unity/commit/d322086a4b1dcae1a4197d7da726deeb035425aa#diff-e42742dcb744df86ea36fa18292a0c557ae8cbe4d5b458a2217dbbe6160067f9R612)... I'll check it out.

**Comment by kumaS-nu** [comment]
In previous versions of Unity, it would throw an exception, and I would grab it. But apparently, the new version of Unity changed to output the error directly to the console without throwing an exception.

**Comment by NoTuxNoBux** [comment]
Just a hunch, but looking at https://github.com/kumaS-nu/NuGet-importer-for-Unity/commit/d322086a4b1dcae1a4197d7da726deeb035425aa#diff-e42742dcb744df86ea36fa18292a0c557ae8cbe4d5b458a2217dbbe6160067f9R612 (not sure if that is the latest code), are you sure that the message didn't just change and it's now hitting the `throw` below, rethrowing the exception?

Also, you might want to catch `HttpException e` instead and check for `e.StatusCode == HttpStatusCode.NotFound` (or similar) instead to avoid the message changing in the future :slightly_smiling_face: .
