### ISSUE TITLE
Enhance path matching pattern of analyzer

### ISSUE THREAD

**Issue by chika-chang** [kumaS-nu/NuGet-importer-for-Unity#47]
**Is your feature request related to a problem? Please describe.**
I tried to add [`MessagePackAnalyzer`](https://learn.microsoft.com/en-us/nuget/guides/analyzers-conventions), but the path of the package does not match the path matching pattern of the analyzer in [`NuGetAnalyzerImportSetting`](https://github.com/kumaS-nu/NuGet-importer-for-Unity/blob/main/NuGetImporterForUnity/Packages/NuGet%20Importer/Editor/NuGetAnalyzerImportSetting.cs#L48), so after importing it Unity will scream in the console.

**Describe the solution you'd like**
Change the path matching pattern of the package, e.g. `analyzers[/\\]dotnet[/\]`

**Describe alternatives you've considered**
- ~~Do not use `MessagePackAnalyzer`~~
- Manually add `MessagePackAnalyzer` plugin
- Suggest `MessagePackAnalyzer` modify nuget package path
- Suggest `NuGet-importer-for-Unity` modify analyser's path matching pattern

**Additional context**
- `MessagePackAnalyzer`'s analyser path `Packages/org.nuget.messagepackanalyzer/analyzers/dotnet/MessagePackAnalyzer.dll`
- [Analyzer NuGet formats](https://learn.microsoft.com/en-us/nuget/guides/analyzers-conventions)

**Comment by kumaS-nu** [comment]
Thanks for the suggestion.
I'll make the changes based on the documentation you shared. (It will be almost the same as your example.)
