### ISSUE TITLE
[Feature request] Option for mark libraries as "Provided by Unity"

### ISSUE THREAD

**Issue by shirok1** [kumaS-nu/NuGet-importer-for-Unity#49]
Hello. I would like to install `LanguageExt.Core` with this plugin, which depends on `Microsoft.CSharp`. But `Microsoft.CSharp` is already provided by Unity Mono runtime, making a compile conflict error. If manually removing the generated package in package manager, code can be correctly compiled but it will still suggest to install `Microsoft.CSharp`, which is quite annoying.

**Comment by kumaS-nu** [comment]
Hi. Thank you for the report.
I'll add a package ignore list, which we can customize. I'll set ignore packages like `Microsoft.CSharp` by default.
