### ISSUE TITLE
Add assembly definition for analyzers

### ISSUE THREAD

**Issue by chikacc** [kumaS-nu/NuGet-importer-for-Unity#54]
**Is your feature request related to a problem? Please describe.**

Currently, when using the NuGet-importer-for-Unity package, the static code analysis tools run on the entire codebase, which can be time-consuming and hinder development productivity.

**Describe the solution you'd like**

We would like to request the addition of assembly definition files to the NuGet-importer-for-Unity package, so that we can specify which assemblies the static code analysis tools should analyze. This would allow us to split the codebase into smaller, more manageable chunks and reduce the time it takes for the tools to run.

**Describe alternatives you've considered**

We have considered manually adding assembly definition files to our project, but this would require extra effort and may not be a viable solution for everyone using the package.

**Additional context**

As mentioned in the Unity documentation [Roslyn analyzers and source generators](https://docs.unity3d.com/Manual/roslyn-analyzers.html), "Assembly definition files let you specify which files belong in a particular assembly. Analyzers use this information to determine the scope of their analysis." Adding assembly definition files to the NuGet-importer-for-Unity package would greatly improve the efficiency and usability of the static code analysis tools for all users of the package.

---

This issue was conceived by Chika Chang and translated by ChatGPT.

**Comment by kumaS-nu** [comment]
I've been so busy that time has passed...

Adding assembly definition file for the analyzer is a good idea. And I considered the following additional ideas.
- Should I automatically add an assembly definition file for the library or not?
- Should I set up dependencies to the assembly definition file or not?


After some tests, I decide not to implement the additional ideas for the following reasons.
- Libraries normally are distributed as a built form (.dll or .so).
- The assembly definition file for the analyzer is used to control the scope.

---------------------------
This comment was translated by  DeepL
