### ISSUE TITLE
[BUG] Download number render wrong

### ISSUE THREAD

**Issue by SettingDust** [kumaS-nu/NuGet-importer-for-Unity#61]
**Describe the bug**
It's negative number in some package
![image](https://github.com/kumaS-nu/NuGet-importer-for-Unity/assets/19922286/00b42516-193f-429c-b828-52120461f0d1)

**Comment by kumaS-nu** [comment]
There are too many downloads, and it is overflowing.
So I'll change the data type from int to long.
