### ISSUE TITLE
[BUG] Installed package not updated

### ISSUE THREAD

**Issue by SettingDust** [kumaS-nu/NuGet-importer-for-Unity#62]
**Describe the bug**
I've installed in a fresh project but the installed is empty
![image](https://github.com/kumaS-nu/NuGet-importer-for-Unity/assets/19922286/a2ef368b-35d1-462a-bd02-ad2086f75924)

**Comment by kumaS-nu** [comment]
I made a terrible mistake.
This bug was made in a new feature (asmdef auto-generation for Analyzer).
I will fix it ASAP.
