### ISSUE TITLE
Invalid operation should attach detail such as stacktrace or detailed message

### ISSUE THREAD

**Issue by SettingDust** [kumaS-nu/NuGet-importer-for-Unity#67]
**Is your feature request related to a problem? Please describe.**
Can't know the reason of a rollback. Just failed
The log to unity debug will be cleared after rollback that triggering reinstall packages

**Comment by kumaS-nu** [comment]
It would be nice to show errors, but the display space is too small to show stack traces. Therefore, showing only errors and the stack trace as an error log in the console would be better.
